test(tools) : Mocking test
assetbox/assetbox pull request #15
Opened 2023-05-03 08:38 UTC by Hoonveloper

### 유닛테스트를 위한 함수 및 모듈 모킹
1. manual mocking을 통해 lilconfig, fs모듈 모킹
2. process.cwd() 함수 모킹하여 memfs로 만든 가상 레포지토리의 절대경로로 리턴 값 고정

### 가상 레포지토리 종류
1. NormalRepository - 정상적인 레포지토리
2. NoAssetPathsRepository - assetbox.config.cjs에 assetPaths가 빈 배열인 레포지토리
3. NoAssetConfigRepository - assetbox.config.cjs가 없는 레포지토리

### 유닛테스트
tools 모노레포 내에서 구현한 함수 단위로 유닛테스트를 진행하였음
1. MockingRepository.test.ts : 가상 레포지토리를 잘 만드는지 테스트
2. readAssetBoxConfig.test.ts :  3가지 가상 레포지토리에서  readAssetBoxConfig.ts 의 리턴값 또는 에러가 적절한지 테스트
3. findAssetFiles.test.ts: 3가지 가상 레포지토리에서 findAssetFiles.ts의 리턴값 또는 에러가 적절한지 테스트

2023-05-03 09:49 UTC, gronxb reviewed
어려운 파일 시스템 모킹하느라 수고 많으셨습니다 ! 몇가지 리뷰 남겨요.

2023-05-03 09:49 UTC, gronxb commented on packages/tools/tsconfig.json
> +    "__mock__"
요거 좀 이상해서 "__mocks__/**/*" 하나로 바꿔주세요 !

2023-05-03 09:49 UTC, gronxb commented on turbo.json
> +      "inputs": ["packages/tools/**/*.ts", "packages/tools/src/*.ts"]
왼쪽 오른쪽 똑같은 느낌이라, 왼쪽 하나만 써주세요.

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/utils/mockRepository.ts
> +export const createNormalMockRepositry = (cwd: string) => {
`createNormalMockRepositry` 이랑 `createNoAssetPathsMockRepositry`랑 뭐가 다른가요 ?

그리고 하나 제안만 하자면 !
```js
createMockRepository(cwd, {
    excludeAssetBoxConfig: false
}); // assetbox config 없는 레포 

createMockRepository(cwd); // 일반 레포 
```
이런식으로 가면 중복 코드 많이 없어질 것 같아요 !

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/readAssetBoxconfig.test.ts
> +    test("readAssetBox config", async () => {
test 위에 엔터

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/readAssetBoxconfig.test.ts
> +    test("readAssetBox config", async () => {
test 위에 엔터

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/readAssetBoxconfig.test.ts
> +      expect(config).toStrictEqual({
expect 위에 엔터

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/readAssetBoxconfig.test.ts
> +      spy.mockReturnValue("/test/normal");
mockClear하고 return value하기 보다는
각 describe 당
beforeEach =>  mockReturnValue
afterEach => mockClear 
해서 
describe 별로 spy 유지할 수 있을 듯요

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/readAssetBoxconfig.test.ts
> +spy.mockReturnValue("/test");
밑에 리뷰를 반영한다면 mockReturnValue는 beforeEach에만 존재

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/mockRepository.test.ts
> +    spy.mockClear();
afterEach 동일 그리고 해당 코드 전반적으로 개행 부탁해용

2023-05-03 09:49 UTC, gronxb commented on packages/tools/src/__test__/findAssetFiles.test.ts
> +      spy.mockClear();
여기도 afterEach

2023-05-03 09:49 UTC, gronxb commented on packages/tools/package.json
> +    "lilconfig": "^2.1.0",
lilconfig 위에 dependency로 옮겨주세용

2023-05-03 09:49 UTC, gronxb commented on packages/tools/babel.config.cjs
> +};
이거 추가한 이유가 뭔가요 ??

2023-05-03 09:49 UTC, gronxb commented on packages/tools/__mocks__/lilconfig.js
> +        : null,
createNoAssetboxConfigMockRepositry 를 대응하려고 이렇게 한 것 같은데, 그러면 이 코드랑 mock 코드랑 강하게 결합되어 버리니까, mock repository가 늘어날때마다 이 코드도 대응해야해요.

그리고 assetbox.config.js가 없다면 기본값으로 반환해버리는데, 차리리 null을 뱉는게 맞는 것 같아요.

2023-05-03 10:59 UTC, gronxb commented on .github/workflows/integration.yml
> +      - name: Mock Test
Unit Test Check ㄱㄱ

2023-05-04 03:14 UTC, gronxb requested changes
거의 다 왔습니다

2023-05-04 03:14 UTC, gronxb commented on packages/tools/src/types.ts
> +};
이거 안쓰는 타입 같아요 !

2023-05-04 03:14 UTC, gronxb commented on packages/tools/src/__test__/utils/mockRepository.ts
> +export const createNormalMockRepositry = (cwd: string) => {
`createMockRepository` 가 지원됐기 때문에, 밑에 함수 `createNormalMockRepositry` 등 지워주시면 될 것 같아요

2023-05-04 03:14 UTC, gronxb commented on packages/tools/__mocks__/lilconfig.js
> +        : null,
search가 async니까 vol.readFileSync 말고 vol.readFile promise 있을 것 같은데 그거 반환하면 좋을 것 같고,

굳이 조건으로 딱딱 안 나누고 어차피 JSON이 잘 읽힐거기 때문에 밑에 처럼만 하면 되지 않아요 ?
```
return vol.readFileSync(
    path.resolve(process.cwd(), "assetbox.config.json"),
    "utf-8"
)
```

2023-05-04 06:42 UTC, Hoonveloper commented on packages/tools/__mocks__/lilconfig.js
> +        : null,
테스트에서 assetbox.config.json이 없는 케이스가 있어서 

```
vol.existSync() : boolean
```
구문을 통해 유무를 체크해야합니다.
exists, readfile을 쓰지 않은 이유는 콜백함수를 넣어야하고 리턴값이 void인 경우도 있기 때문입니다.
또, 존재한다면 assetpaths 배열이 빈 배열인지 체크도 해야합니다.



```
return vol.readFileSync(
    path.resolve(process.cwd(), "assetbox.config.json"),
    "utf-8"
)
```

위 코드를 사용하지 않는 이유는 config.json의 구조를 보시면 됩니다.

lilconfig.search()의 리턴값은 위 리턴값과 다릅니다. 
```
{
config: assetbox.config.json의 경로
filepaths : {
assetpaths: []
}
```

2023-05-04 06:50 UTC, gronxb commented on packages/tools/__mocks__/lilconfig.js
> +        : null,
exists는 👍 없으면 null 반환하는거 맞네요.

> 존재한다면 assetpaths 배열이 빈 배열인지 체크도 해야합니다.

이 부분이 이해가 가지 않는데, JSON 파일이 `{ assetPaths: [] }` 이렇게 생겼고 JSON.parse(readFile(왼쪽 값)) 이렇게하면 assetPaths는 빈 배열로 오지 않아요 ?

마지막 리턴값이 다르다는 것은 인정하는 부분이라 새로 제안합니다.
아래와 같이 한다면 호환이 안될까요 ?
```
const data = JSON.parse(vol.readFileSync(
    path.resolve(process.cwd(), "assetbox.config.json"),
    "utf-8"
));
 return {
   configFilePath: path.resolve(process.cwd(), "assetbox.config.json"),
   ...data,
}
```

2023-05-04 07:52 UTC, gronxb approved these changes
LGTM👍

2023-05-04 07:53 UTC, merged