Merge dup file set
assetbox/assetbox pull request #23
Opened 2023-05-11 13:29 UTC by Hoonveloper

### 1. mergeDupeFileSet 테스트 코드 작성
### 2. mergeDupeFileSet 함수 실제 구현
- Parameters
> - DupeFiles: fileHash가 같은 파일 리스트 
> - NewPathAndName: 병합할 파일의 위치와 새로운 이름 (확장자 제외, 확장자는 DupeFiles의 첫번째 파일의 확장자로 지정)

- Return
> - isMerged: 병합에 성공했는지
> - NewPathAndName: 병합된 파일의 위치와 새로운 이름 (확장자 포함)

### 3. trpc 모노레포 내부 api 추가
- mergeAsset API, mergeDupeFileSet 연동
-  trpc/package.json 수정 (@assetbox/tools)

### 4. __test__ 디렉토리 삭제
- 함수들과 같은 디렉토리( .../tools/src)에 위치하도록 변경

2023-05-11 13:38 UTC, Hoonveloper commented on packages/tools/src/mergeDupeFileSet.ts
> +import { resolve } from "path";
맞네요 반영하겠씁니다~~

2023-05-11 13:45 UTC, moonchop reviewed
👍

2023-05-11 13:45 UTC, moonchop commented on packages/tools/src/mergeDupeFileSet.ts
> +import { resolve } from "path";
mockRepository.test.ts 파일도 위와 동일하게 확인해주세요~

2023-05-11 13:45 UTC, moonchop commented on packages/tools/src/mergeDupeFileSet.ts
> +    throw new Error("Error Occured in mergeDupeFileSet: " + e + "");
이렇게 바꾸는건 어떨까요?
```js
`${newPathAndName}.${fileExtension}`
```

`템플릿 리터럴`을 사용하면 코드가 더 명확하고 간결해지며, 긴 문자열을 작성할 때도 더 편리합니다.

2023-05-11 14:06 UTC, gronxb requested changes

2023-05-11 14:06 UTC, gronxb commented on packages/tools/src/mergeDupeFileSet.ts
> +    });
위에 newPathAndName => savePath로 바꾼다면 안에 확장자까지 같이 올 예정이라서 확장자 구하는거랑 더하는 건 안해도 될 것 같습니다 !

2023-05-12 04:14 UTC, devnak commented on packages/tools/src/mergeDupeFileSet.ts
> +    });
renameSync, unlinkSync를 통해서 이름변경, 경로변경, 파일삭제 로직이 진행되는건가요?

2023-05-12 04:15 UTC, devnak commented on packages/tools/src/mergeDupeFileSet.ts
> +    });
renameSync, unlinkSync를 통해서 이름변경, 경로변경, 파일삭제 로직이 진행되는건가요?

2023-05-12 14:29 UTC, Hoonveloper commented on packages/tools/src/mergeDupeFileSet.ts
> +    });
네 맞아요 @devnak

2023-05-12 14:33 UTC, gronxb approved these changes

2023-05-12 14:33 UTC, merged