UI Components: Input, Button, ButtonGroup
assetbox/assetbox pull request #26
Opened 2023-05-15 11:02 UTC by devnak

# UI Components

## Input

### Usage
`Input.tsx`
- className을 통해 크기 및 Custom CSS 적용
- endAdornment를 통해 이미지 삽입 가능
- outline 없는 input은 noOutline적용
```js
<Input
        noOutline
        className="w-[654px] h-12"
        endAdornment={<Logo className="w-14 h-14" />}
      />
```

## Button
### Usage
`Button.tsx`
- className을 통해 크기 및 Custom CSS 적용
- variant를 통해 blue(primary), red(danger), group(group) 버튼 선택 가능
- Default variant는 primary.
```js
<Button
        variant="primary"
        endAdornment={<Logo className="w-14 h-14" />} 
      >Merge
</Button>
```

## ButtonGroup
### Usage
`ButtonGroup.tsx`
```js
<ButtonGroup defaultValue="Icons">
        <ButtonGroup.Button className="w-24 h-12">Icons</ButtonGroup.Button>
        <ButtonGroup.Button className="w-24 h-12">Images</ButtonGroup.Button>
        <ButtonGroup.Button className="w-24 h-12">Animations</ButtonGroup.Button>
</ButtonGroup>
```

2023-05-15 11:57 UTC, gronxb requested changes

2023-05-15 11:57 UTC, gronxb commented on packages/manager/src/components/ui/Button.tsx
> +  variant?: "primary" | "danger" | "group";
직접 쓰는 것보다 타입 추론으로 받아올 수 있을 것 같은데
```
variant: ReturnType<typeof  buttonVariants>["variants"]["variant"] 
```

요런 느낌 ?

2023-05-15 11:57 UTC, gronxb commented on packages/manager/src/components/ui/ButtonGroup.tsx
> +      value={children as string}
이거는 왜 children을 넣고, 그리고 string으로 바꾸나요 ?

2023-05-15 11:57 UTC, gronxb commented on packages/manager/src/components/ui/Input.tsx
> +  noOutline?: boolean;
요거 역시 noOutline이 아니라
ReturnType<inputVariants>["variants"] 같은 느낌으로 가능할 수 도 ??

2023-05-18 03:03 UTC, gronxb commented on packages/manager/src/components/ui/Button.tsx
> +  variant?: "primary" | "danger" | "group";
<img width="902" alt="image" src="https://github.com/assetbox/assetbox/assets/41789633/326b40b0-e77d-4ff8-9f9c-3d3b86cf467d">
https://cva.style/docs/getting-started

공식 문서에서도 하는 방법 확인

2023-05-18 06:59 UTC, gronxb approved these changes

2023-05-18 07:01 UTC, devnak commented on packages/manager/src/components/ui/Input.tsx
> +  noOutline?: boolean;
반영했습니다

2023-05-18 07:01 UTC, merged