Upload asset API
assetbox/assetbox pull request #44
Opened 2023-06-04 17:20 UTC by Hoonveloper

파일 하나씩 업로드하는 API 요청입니다. 
- Http Method : Post
- Request
Body : form-data, savePath (저장할 경로)
<img width="569" alt="image" src="https://github.com/assetbox/assetbox/assets/77804950/43e22f64-ac24-454b-8baa-b58a78ef66cd">

- Response
실패 : StatusCode= 400,  "message":""Asset upload Failed" 
성공 : statusCode = 201, "message": "Asset uploaded successfully"

- 주의사항: form-data보다 savePath를 먼저 body에 넣어주세요. 
(클라이언트가 바디로 보내는 순서에 따라 multer에 req.body가 들어가지 않을 수도 있기 때문입니다.)

2023-06-04 17:32 UTC, gronxb commented on packages/cli/src/commands/manage.ts
> +import multer from "multer";
제거

2023-06-04 17:35 UTC, gronxb requested changes
파일 시스템에서 `/` << 이거 써야할 때

import {sep} from "path"; 해서 sep으로 대체해주세요.

sep << window에선 \ , 그 외엔 / 이걸로 대체됨

그리고 문자열을 더할 땐 `${}` 이렇게 템플릿 리터럴을 사용하거나 배열로 묶어서 한번에 join해주세요.

2023-06-04 17:35 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +        console.log(savePath);
제거

2023-06-04 17:35 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +        if (!fs.existsSync(cwd() + "/" + savePath)) {
`[cwd(), savePath].join(sep);`

2023-06-04 17:35 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +          fs.mkdirSync(cwd() + "/" + savePath);
`[cwd(), savePath].join(sep);`

2023-06-04 17:35 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +        cb(null, cwd() + "/" + savePath);
`[cwd(), savePath].join(sep);`

반복해서 쓰이는 것 같은데 상단에 변수 하나 선언하는게 어떨지

2023-06-04 17:35 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +        cwd() + "/" + req.body.savePath + "/" + req.file?.originalname
[cwd(), req.body.savePath, req.file?.originalname].filter(Boolean).join(sep);

2023-06-05 09:58 UTC, gronxb requested changes

2023-06-05 09:58 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +        }
생각해보니 
[cwd(), savePath].join(sep)
이거랑 똑같은게
path.resolve(cwd(), savePath); 이거네요

checkPath => resolvePath 변경

```
const resolvePath = savePath ? path.resolve(cwd(), savePath) : req.body.savePath;
```

2023-06-05 09:58 UTC, gronxb commented on packages/cli/src/commands/uploadFileRouter.ts
> +          console.log("create dir");
remove

2023-06-06 08:11 UTC, moonchop approved these changes
lgtm

2023-06-06 08:11 UTC, moonchop approved these changes
lgtm

2023-06-06 08:12 UTC, merged